repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0  # Latest stable version
    hooks:
    -   id: black
        language_version: python3.12
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2  # Latest stable version
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
